Added URL validations.
dev-yoonik/yk-utils-python pull request #13
Opened 2022-03-11 17:11 UTC by jppdpf

Added BadURL exception.
Updated changelog and yk-utils package version.

2022-03-14 13:52 UTC, vitormcpedro requested changes

2022-03-14 13:52 UTC, vitormcpedro commented on yk_utils/objects/__init__.py
> +    get_url_domain, is_valid_url, get_url
Maybe it is better to put these new functions in a "web" directory?

2022-03-14 18:24 UTC, jppdpf commented on yk_utils/objects/object_operations.py
> +    return urlparse(url).hostname.split('.')[-2]
Ok, I'll also update the function name to get_urL_hostname.

2022-04-01 14:20 UTC, dev-yoonik approved these changes

2022-04-01 14:22 UTC, merged